# Generated by Django 3.2.10 on 2024-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0008_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='experience',
            field=models.TextField(default='one year', max_length=255),
            preserve_default=False,
        ),
    ]
